### ISSUE TITLE
Can't believe this is even proposed.

### ISSUE THREAD

**Issue by jmlingeman** [RupertBenWiser/Web-Environment-Integrity#113]
I notice that this wasn't posted to a Google official repo. Trying to making it look more "grassroots" are we?

Ad company trying to force everyone to watch their stupid ads that no one wants to see. Maybe when hundreds of millions of people around the world install software specifically designed to block the annoying crap you want to force us to look at, it means your business model is bad. Not that users are wrong.

**Comment by scanlime** [comment]
It's a heck of a thing to post on one's personal github for sure.
