### ISSUE TITLE
Have you ever stopped to consider that you're the bad guys?

### ISSUE THREAD

**Issue by AmigaEnjoyer** [RupertBenWiser/Web-Environment-Integrity#127]
Nobody wants this. This idea is bad and you should feel bad. This is some 1900s corporate trust stuff happening all over again. Stop trying to monopolize the internet.

**Comment by mokrates** [comment]
![are-we-the-baddies-bad](https://github.com/RupertBenWiser/Web-Environment-Integrity/assets/9881544/c6593fe0-86dc-4729-97ad-f7fc78021ca0)
