### ISSUE TITLE
This will make the web stupid, and it will be wholly ineffective

### ISSUE THREAD

**Issue by dlenski** [RupertBenWiser/Web-Environment-Integrity#45]
Bootstrapping trust and remote attestation are very hard problems, and require careful control of every layer of the system _from the silicon up_.

On the other hand, displaying ads (or serving up DRM'ed media, for that matter) pretty much being willing to go wherever the eyeballs are.

The two are hopelessly in tension with each other.

You're gonna build some crummy DRM obfuscation, it's going to be a massive annoyance, somebody's gonna implement it in a slipshod way on an easily hackable system, and ad-block-wielding Linux-using chaos monkeys like me are going to figure out how to spoof it. 🤷🏻‍♂️

---

I'm one of the maintainers of [OpenConnect](https://GitLab.com/openconnect/openconnect), the multiprotocol VPN client; we've figured out the wire protocol for every ekstra speshul proprietary tunnelling protocol on the planet, and I've also reverse engineered and reimplemented the extraordinarily dumb obfuscated protocol for provisioning RSA soft-tokens (see [dlenski/rsa_ct_kip](http://GitHub.com/dlenski/rsa_ct_kip)).

**Comment by yoavweiss** [comment]
Dup of #28
