### ISSUE TITLE
This idea is bad and you should feel bad

### ISSUE THREAD

**Issue by selfagency** [RupertBenWiser/Web-Environment-Integrity#47]
You're going to destroy the ability for browser automation tools to function so that you can keep shoving Google Ads into our eye holes and blocking scrapers from collecting data? Congrats on creating yet the latest effort to murder the open web and presenting it as a concern of users who want to visit "expensive" websites. You should be embarrassed and ashamed. 2023 and Google wants to bring back ActiveX, smh.

**Comment by DanGrizzly** [comment]
Gatekeeping API working out great for Reddit and Twitter right now too

**Comment by cybik** [comment]
@selfagency as soon as the beancounters and pencil pushers took over, they became that which they were the solution for.

**Comment by thany** [comment]
This is what you get when we allow a company whose core business is advertising, to build up a near-monopoly in browsers.

Like if Marlboro was a giant multinational advertising company, they too would use that to monopolise their cigarettes, and we'd all still be smoking our lungs pitch black.

**Comment by yoavweiss** [comment]
Dup of #28
