### ISSUE TITLE
do not

### ISSUE THREAD

**Issue by alyxbb** [RupertBenWiser/Web-Environment-Integrity#48]
do  not

**Comment by ThatOneCalculator** [comment]
so true!! indeed, do not. bad.

**Comment by yoavweiss** [comment]
Closing as non-constructive

**Comment by scanlime** [comment]
> Closing as non-constructive

I don't assume that constructive outcomes are better in this case. What are we constructing, and for who?

I see you're concerned about "constructive" feedback [here](https://blog.yoav.ws/posts/web_platform_change_you_do_not_like/) too, but sometimes we have to have a larger conversation about goals first.

**Comment by alyxbb** [comment]
judging by the fact you've had 30 issues made asking you to not go forward with the proposal maybe you should not go forward with the proposal

**Comment by ThatOneCalculator** [comment]
No, that'd make too much sense 🥴
