### ISSUE TITLE
hm today i will propose this very useful web standard that will surely work out with no backlash whatsoever

### ISSUE THREAD

**Issue by chfour** [RupertBenWiser/Web-Environment-Integrity#52]
<-- clueless

**Comment by yoavweiss** [comment]
Closing as non-constructive

**Comment by digikitty-x86** [comment]
Psssssssssssht the only thing here that I'd consider non-constructive is implementing that API

**Comment by dakrk** [comment]
can we give this a True...

**Comment by teh-maxh** [comment]
> Closing as non-constructive

Can you do that for the entire idea?
