### ISSUE TITLE
Would it be that hard not to create oppressive web standards that provide no real world benefit? 

### ISSUE THREAD

**Issue by digikitty-x86** [RupertBenWiser/Web-Environment-Integrity#53]
_The answer is no_, it turns out stunting yours and others browsers in ways that impact important aspects such as accessibility in favour of capitalistic practices is _infact_ a bad idea, there's no way going through with this won't lead to an antitrust lawsuit-

**Comment by scanlime** [comment]
I've never worked at google but i'm guessing the hard part is telling the higher-ups "no"
