### ISSUE TITLE
Cease Immediately

### ISSUE THREAD

**Issue by videotoblinski** [RupertBenWiser/Web-Environment-Integrity#58]
This is the worst idea in the history of web browsing. Tim Berners-Lee could look at this and shed a tear. All of the folks responsible for the development of the interconnected web are staring at you, right now, and crying. **_They're crying._** It's all your fault. What is this **_bunkum?_** This **_drivel_** will simply _drive_ everyone away from using Google's godawful web browser. If Mozilla doesn't add this, this **_rot_** is going to see some usage numbers go up for Firefox.

tl;dr: cease

**Comment by yoavweiss** [comment]
Dup of #28
