### ISSUE TITLE
Could you guys please stop trying to create a 1984 dystopia every 5 minutes?

### ISSUE THREAD

**Issue by th3maid** [RupertBenWiser/Web-Environment-Integrity#63]
We need a safety and trusted client side "verification" to ensure Google decide all content on the internet is valid or not, block people live free of extreme abusive and intrusive surveillance ad system and make impossible to normal access web sites and apps outside big tech hands.
The next step involves implementing a social ID system and a high level of social score to regulate internet access.
Could you guys please stop trying to create a 1984 dystopia every 5 minutes?

**Comment by yoavweiss** [comment]
Dup of #28
