### ISSUE TITLE
Feature Request: Whitelisted Websites 

### ISSUE THREAD

**Issue by jmillerv** [RupertBenWiser/Web-Environment-Integrity#65]
Rather than go through this long process, can we skip attestation and just ship Chrome with an approved list of websites users are allowed to visit? We need to prioritize sites that encourage transactions. Perhaps organizations can pay to be on the whitelist. We want to avoid letting people have access to anything that blocks ads but we may need to take a step further and only whitelist sites that won't possibly teach people how to create their own browsers, subvert DRM, or avoid advertisements.

**Comment by Howdoesthiswo** [comment]
Why even allow websites? Users exist just to make them money, why go through effort to provide any service to them at all?

**Comment by Sqaaakoi** [comment]
Why not make a new protocol, designed purely about security and Capitalism™️ for all sorts of e-commerce and propietary media sharing?
