### ISSUE TITLE
Keep Yourself Safe

### ISSUE THREAD

**Issue by safiire** [RupertBenWiser/Web-Environment-Integrity#83]
I'd just like to let you know that this proposal will cause all you authors to be reviled for the rest of time.

So please keep yourself safe and recant this immediately, it's not worth whatever google is paying you.

**Comment by chetchaka** [comment]
Not just reviled. This could be considered criminal activity under antitrust laws.
To quote [twhaples' comment](https://github.com/RupertBenWiser/Web-Environment-Integrity/issues/28#issuecomment-1642392606):

> I would like to respectfully add my suggestion that Ben Wiser (Google), Borbala Benko (Google), Philipp Pfeiffenberger (Google), and Sergey Kataev (Google) all take this opportunity to engage a personal lawyer and seek legal advice, i.e. do not defer to the corporate counsel (Google), who may not have their best interests in mind. Antitrust law is real. Some violations are crimes.
