### ISSUE TITLE
Feature request: block websites entirely

### ISSUE THREAD

**Issue by 0x4d6165** [RupertBenWiser/Web-Environment-Integrity#93]
this doesn't go far enough; non standard browsers shouldn't be allowed to operate at all. ad blocking should result in your cpu melting into slag

**Comment by HellyTubbies** [comment]
so true

**Comment by teh-maxh** [comment]
But then you might still buy another computer and use it to block ads.

**Comment by lunaneff** [comment]
don't worry, the other computer will also melt before you get a chance to use it
