### ISSUE TITLE
Feature request: remove all other non-Google useragents from client devices

### ISSUE THREAD

**Issue by coricarson** [RupertBenWiser/Web-Environment-Integrity#94]
This is meant to harm users, but they might ditch Google products for a competing useragent to avoid that harm.

Chrome should continue this effort to remove all other useragents (browsers or otherwise) found installed on users devices'. This will maximize profits and uplift the Chrome brand.

**Comment by TheMemeSniper** [comment]
also install hostsfile entries to redirect download links for other useragents to the chrome download page

**Comment by Kusanalee** [comment]
if using a non standard browser, all websites must redirect to chrome download page
