### ISSUE TITLE
shopping list

### ISSUE THREAD

**Issue by Lana-chan** [RupertBenWiser/Web-Environment-Integrity#96]
sorry hold on i just need to write this down somewhere

- [ ] milk
- [ ] soda
- [ ] snacks
- [ ] carrots
- [ ] onions
- [ ] beef
- [ ] frozen burgers
- [ ] biscuits
- [ ] chocolate
- [ ] cheese
- [ ] chips, no starch

**Comment by Kusanalee** [comment]
i agree that seems like a good shopping list

**Comment by miss-programgamer** [comment]
Can you get me some chips while you're there?

**Comment by Lana-chan** [comment]
thanks i try to keep on top of things in my kitchen

**Comment by Lana-chan** [comment]
> Can you get me some chips while you're there?

do you have dietary restrictions

**Comment by miss-programgamer** [comment]
Just not starch based thanks

**Comment by Lana-chan** [comment]
ok i'll see what they have !

**Comment by khbsd** [comment]
i'd like some low-sodium chickpeas

gonna roast them later

**Comment by Coo-ops** [comment]
LGTM

**Comment by asthargf** [comment]
Please, add some vegan gluten-free icecream too. Vanilla or chocolate are ok! Thank you ^_^
