### ISSUE TITLE
Some thoughts on this proposal

### ISSUE THREAD

**Issue by salarua** [RupertBenWiser/Web-Environment-Integrity#99]
44 45 41 54 48 20 54 4F 20 46 41 53 43 49 53 54 53 2C 20 45 41 54 20 54 48 45 20 52 49 43 48 2C 20 41 4E 44 20 49 20 48 4F 50 45 20 45 56 45 52 59 20 54 45 43 48 42 52 4F 20 46 55 43 4B 46 41 43 45 20 47 45 54 53 20 45 58 50 4C 4F 53 49 56 45 20 44 49 41 52 52 48 45 41 20 44 55 52 49 4E 47 20 48 49 53 20 42 49 47 20 4B 45 59 4E 4F 54 45

**Comment by Kusanalee** [comment]
69 20 61 67 72 65 65

**Comment by asthargf** [comment]
49 20 41 47 52 45 45 20 54 4F 4F

**Comment by Sqaaakoi** [comment]
49 20 41 4C 53 4F 20 41 47 52 45 45 0A

**Comment by lunaneff** [comment]
46 75 63 6B 20 47 6F 6F 67 6C 65 2C 20 62 75 74 20 6E 6F 74 20 69 6E 20 74 68 65 20 73 65 78 75 61 6C 20 77 61 79 20 62 65 63 61 75 73 65 20 74 68 65 79 20 6D 69 67 68 74 20 65 6E 6A 6F 79 20 74 68 61 74
